# Generated by Django 3.1.3 on 2020-11-05 16:10

from django.conf import settings
import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Calendar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('NOT PLANTED', 'Not planted yet'), ('OUTSIDE', 'Planted outside'), ('INSIDE', 'Planted inside')], max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Climate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('objectid', models.IntegerField()),
                ('koppengeig', models.IntegerField()),
                ('koppenge_1', models.IntegerField()),
                ('gridcode_c', models.CharField(max_length=3)),
                ('gridcode_1', models.CharField(max_length=14)),
                ('gridcode_2', models.CharField(max_length=11)),
                ('gridcode_3', models.CharField(max_length=21)),
                ('koppenge_2', models.IntegerField()),
                ('geom', django.contrib.gis.db.models.fields.PolygonField(srid=4326)),
            ],
        ),
        migrations.CreateModel(
            name='FAQ',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.TextField()),
                ('question', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=4326)),
                ('profile_image', models.CharField(max_length=500)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Plant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('min_temperature', models.IntegerField()),
                ('max_temperature', models.IntegerField()),
                ('water_every_X_days', models.IntegerField()),
                ('name', models.CharField(max_length=100)),
                ('pet_safe', models.BooleanField()),
                ('harvest_every_X_days', models.IntegerField()),
                ('repot_every_X_years', models.IntegerField()),
                ('feed_every_X_months', models.IntegerField()),
                ('harvest_in_X_days', models.IntegerField()),
                ('light', models.CharField(choices=[('LOW', 'Low light'), ('MEDIUM', 'Medium light'), ('HIGH', 'High light')], default='MEDIUM', max_length=6)),
                ('humidity', models.CharField(choices=[('LOW', 'Low humidity'), ('MEDIUM', 'Medium humidity'), ('HIGH', 'High humidity')], default='MEDIUM', max_length=6)),
                ('tracked', models.ManyToManyField(through='ZoeDB.Calendar', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.DateField()),
                ('status', models.CharField(choices=[('WATER', 'Watered the plant'), ('PLANT', 'Planted from cutting'), ('SOW', 'Sowed from seed'), ('FEED', 'Fertilized the plant'), ('REPOT', 'Plant repotted'), ('MOVE', 'Move outside/inside'), ('HARVEST', 'Harvested'), ('TRANSPLANT', 'Transplanted'), ('PRUNE', 'Prunned')], max_length=30)),
                ('calendar', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ZoeDB.calendar')),
            ],
        ),
        migrations.AddField(
            model_name='calendar',
            name='plant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ZoeDB.plant'),
        ),
        migrations.AddField(
            model_name='calendar',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
