# Generated by Django 3.1.3 on 2020-11-12 23:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ZoeDB', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='plant',
            name='image',
            field=models.ImageField(blank=True, upload_to='uploads/plants'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='profile_image',
            field=models.ImageField(blank=True, upload_to='uploads/profile'),
        ),
    ]
