# Generated by Django 3.1.3 on 2020-12-14 23:12

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ZoeDB', '0005_category_post_thread'),
    ]

    operations = [
        migrations.RenameField(
            model_name='climate',
            old_name='geom',
            new_name='wkb_geometry',
        ),
        migrations.RemoveField(
            model_name='climate',
            name='gridcode_1',
        ),
        migrations.RemoveField(
            model_name='climate',
            name='gridcode_2',
        ),
        migrations.RemoveField(
            model_name='climate',
            name='gridcode_3',
        ),
        migrations.RemoveField(
            model_name='climate',
            name='gridcode_c',
        ),
        migrations.RemoveField(
            model_name='climate',
            name='koppenge_1',
        ),
        migrations.RemoveField(
            model_name='climate',
            name='koppenge_2',
        ),
        migrations.RemoveField(
            model_name='climate',
            name='koppengeig',
        ),
        migrations.RemoveField(
            model_name='climate',
            name='objectid',
        ),
        migrations.AddField(
            model_name='climate',
            name='climatecode',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='climate',
            name='gridcode',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='climate',
            name='ogc_fid',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='plant',
            name='climatezones',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=10), blank=True, null=True, size=None),
        ),
    ]
