# Generated by Django 3.1.3 on 2020-12-15 00:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ZoeDB', '0006_auto_20201215_0012'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='location_zone',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
